update frontend dockerfile

diff --git a/.github/workflows/build-frontend.yml b/.github/workflows/build-frontend.yml
--- a/.github/workflows/build-frontend.yml
+++ b/.github/workflows/build-frontend.yml
@@ -24,6 +24,7 @@ env:
 jobs:
   build-frontend:
     runs-on: ubuntu-latest
+    environment: prod
 
     steps:
       - name: Checkout
@@ -54,6 +55,15 @@ jobs:
           fi
           echo "tags=${TAGS}" >> $GITHUB_OUTPUT
 
+      - name: Ensure VITE_API_BASE_URL
+        env:
+          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}
+        run: |
+          if [ -z "$VITE_API_BASE_URL" ]; then
+            echo "ERROR: VITE_API_BASE_URL no está definido en el environment 'prod'."
+            exit 1
+          fi
+
       - name: Build & Push Frontend Service
         uses: docker/build-push-action@v6
         with:
@@ -64,3 +74,5 @@ jobs:
           tags: ${{ steps.tags.outputs.tags }}
           cache-from: type=gha
           cache-to: type=gha,mode=max
+          build-args: |
+            VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}
